# Notebook f√ºr einfache Test und Blick in die Daten

In [2]:
# Importiere Bibliotheken
import os
import re
import numpy as np
import pandas as pd

In [5]:
# Daten einlesen
data_raw = pd.read_pickle('data_modified/tweets.pkl')

### Tests

In [14]:
# Tweets pro Tag
print(data_raw['2017-10-01':'2018-03-04'].groupby(data_raw['2017-10-01':'2018-03-04'].index.date).count())

            User  Tweet  Retweet  RT_from  Orig_Tweet  Tweet_Participants  \
2017-10-01    66     66       66       28          66                  66
2017-10-02   163    163      163       72         163                 163
2017-10-03   117    117      117       45         117                 117
2017-10-04    72     72       72       36          72                  72
2017-10-05   132    132      132       67         132                 132
2017-10-06    82     82       82       28          82                  82
2017-10-07    91     91       91       29          91                  91
2017-10-08   138    138      138       49         138                 138
2017-10-09   147    147      147       59         147                 147
2017-10-10   179    179      179       77         179                 179
2017-10-11   216    216      216      100         216                 216
2017-10-12   208    208      208      123         208                 208
2017-10-13   120    120      120       55         120                 120
2017-10-14   158    158      158       85         158                 158
2017-10-15   162    162      162       86         162                 162
2017-10-16   125    125      125       79         125                 125
2017-10-17   130    130      130       39         130                 130
2017-10-18   654    654      654      255         654                 654
2017-10-19   277    277      277      112         277                 277
2017-10-20   243    243      243       99         243                 243
2017-10-21   186    186      186       58         186                 186
2017-10-22   177    177      177       45         177                 177
2017-10-23   282    282      282      121         282                 282
2017-10-24   272    272      272      139         272                 272
2017-10-25   386    386      386      189         386                 386
2017-10-26   618    618      618      389         618                 618
2017-10-27   562    562      562      321         562                 562
2017-10-28   606    606      606      277         606                 606
2017-10-29   641    641      641      328         641                 641
2017-10-30   545    545      545      298         545                 545
...          ...    ...      ...      ...         ...                 ...
2018-02-02   734    734      734      337         734                 734
2018-02-03   699    699      699      292         699                 699
2018-02-04   573    573      573      245         573                 573
2018-02-05   779    779      779      330         779                 779
2018-02-06  1111   1111     1111      399        1111                1111
2018-02-07   824    824      824      421         824                 824
2018-02-08   805    805      805      325         805                 805
2018-02-09   857    857      857      362         857                 857
2018-02-10   710    710      710      317         710                 710
2018-02-11   309    309      309      127         309                 309
2018-02-13     5      5        5        1           5                   5
2018-02-14   908    908      908      398         908                 908
2018-02-15   861    861      861      362         861                 861
2018-02-16  1054   1054     1054      446        1054                1054
2018-02-17   731    731      731      330         731                 731
2018-02-18   778    778      778      386         778                 778
2018-02-19   849    849      849      402         849                 849
2018-02-20   919    919      919      392         919                 919
2018-02-21   717    717      717      320         717                 717
2018-02-22   702    702      702      326         702                 702
2018-02-23   662    662      662      304         662                 662
2018-02-24   641    641      641      311         641                 641
2018-02-25   818    818      818      326         818                 818
2018-02-26   845    845      845      352         845                 845
2018-02-27   926    926      926      488         926                 926
2018-02-28   978    978      978      469         978                 978
2018-03-01   873    873      873      385         873                 873
2018-03-02   751    751      751      301         751                 751
2018-03-03   865    865      865      360         865                 865
2018-03-04   627    627      627      321         627                 627

            Reply  Text  Tags  Lang  Link
2017-10-01     66    66    66    66    66
2017-10-02    163   163   163   163   163
2017-10-03    117   117   117   117   117
2017-10-04     72    72    72    72    72
2017-10-05    132   132   132   132   132
2017-10-06     82    82    82    82    82
2017-10-07     91    91    91    91    91
2017-10-08    138   138   138   138   138
2017-10-09    147   147   147   147   147
2017-10-10    179   179   179   179   179
2017-10-11    216   216   216   216   216
2017-10-12    208   208   208   208   208
2017-10-13    120   120   120   120   120
2017-10-14    158   158   158   158   158
2017-10-15    162   162   162   162   162
2017-10-16    125   125   125   125   125
2017-10-17    130   130   130   130   130
2017-10-18    654   654   654   654   654
2017-10-19    277   277   277   277   277
2017-10-20    243   243   243   243   243
2017-10-21    186   186   186   186   186
2017-10-22    177   177   177   177   177
2017-10-23    282   282   282   282   282
2017-10-24    272   272   272   272   272
2017-10-25    386   386   386   386   386
2017-10-26    618   618   618   618   618
2017-10-27    562   562   562   562   562
2017-10-28    606   606   606   606   606
2017-10-29    641   641   641   641   641
2017-10-30    545   545   545   545   545
...           ...   ...   ...   ...   ...
2018-02-02    734   734   734   734   734
2018-02-03    699   699   699   699   699
2018-02-04    573   573   573   573   573
2018-02-05    779   779   779   779   779
2018-02-06   1111  1111  1111  1111  1111
2018-02-07    824   824   824   824   824
2018-02-08    805   805   805   805   805
2018-02-09    857   857   857   857   857
2018-02-10    710   710   710   710   710
2018-02-11    309   309   309   309   309
2018-02-13      5     5     5     5     5
2018-02-14    908   908   908   908   908
2018-02-15    861   861   861   861   861
2018-02-16   1054  1054  1054  1054  1054
2018-02-17    731   731   731   731   731
2018-02-18    778   778   778   778   778
2018-02-19    849   849   849   849   849
2018-02-20    919   919   919   919   919
2018-02-21    717   717   717   717   717
2018-02-22    702   702   702   702   702
2018-02-23    662   662   662   662   662
2018-02-24    641   641   641   641   641
2018-02-25    818   818   818   818   818
2018-02-26    845   845   845   845   845
2018-02-27    926   926   926   926   926
2018-02-28    978   978   978   978   978
2018-03-01    873   873   873   873   873
2018-03-02    751   751   751   751   751
2018-03-03    865   865   865   865   865
2018-03-04    627   627   627   627   627

[154 rows x 11 columns]

In [16]:
# Tweets gesamt
print(data_raw['2017-10-01':'2018-03-04'].info())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 99511 entries, 2017-10-31 09:59:00 to 2017-10-31 09:55:00
Data columns (total 11 columns):
User                  99511 non-null object
Tweet                 99511 non-null object
Retweet               99511 non-null bool
RT_from               46131 non-null object
Orig_Tweet            99511 non-null bool
Tweet_Participants    99511 non-null object
Reply                 99511 non-null bool
Text                  99511 non-null object
Tags                  99511 non-null object
Lang                  99511 non-null object
Link                  99511 non-null object
dtypes: bool(3), object(8)
memory usage: 7.1+ MB
None

In [18]:
# Anzahl der Twitter-Account
data_raw['2017-10-01':'2018-03-04']['User'].nunique()

12091